[[redirects]]
  from = "/blog/:slug"
  to = "/.netlify/functions/blog-post/:slug"
  status = 200
  force = true

[[redirects]]
  from = "/contacto"
  to = "/contacto.html"
  status = 200
  force = true

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200
  force = true
